version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
  redis:
    image: library/redis:6.0.10
    ports:
      - "6379:6379"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    depends_on:
      - db

